export enum ECOMMITEE {
  NONE = "None",
  AGRICULTURE = "AGRICULTURE",
  EDUCATION = "EDUCATION",
  FINANCE = "FINANCE",
  HEALTH = "HEALTH",
  INFRASTRUCTURE = "INFRASTRUCTURE/WATER MAINTENANCE",
  PEACE_ORDER = "PEACE & ORDER",
  RULES_LAWS = "RULES & LAWS ENVIRONMENTAL PROTECTION",
  SPORTS = "SPORTS/BEAUTIFICATION",
  SENIOR_CITIZEN = "SENIOR CITIZEN/PWD",
  WOMEN_S = "WOMEN’S/BCPC",
}
