export enum EPOSITION {
  // BARANGAY
  PUNONG_BARANGAY = "PUNONG BARANGAY",
  COUNCILOR = "COUNCILOR",
  SECRETARY = "SECRETARY",
  TREASURER = "TREASURER",
  BARANGAY_TANOD = "BARANGAY TANOD",
  BARANGAY_HEALTH_WORKERS = "BARANGAY HEALTH WORKER",
  // SK GROUP
  SK_CHAIRMAN = "SK CHAIRMAN",
  SK_COUNCILOR = "SK COUNCILOR",
  SK_MEMBER = "SK MEMBER",
  SK_SECRETARY = "SK SECRETARY",
  SK_TREASURER = "SK TREASURER",
  SK_AUDITOR = "SK AUDITOR",
  SK_FEDERATION_PRESIDENT = "SK FEDERATION PRESIDENT",
}
